name: 卢卡·莫德里奇  Luka Modric
url: https://zb123.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: faculty
    name: 个人 He
  - key: grad
    name: 队友 Teammate
  - key: ugrad
    name: 俱乐部 club
  - key: collab
    name: 合作者 Collaborators


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: zzz Home
    link: /
  - title: 科研项目 Research
    link: /research.html
  - title: 论文 Publications
    link: /publications.html
